# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       lnav

# >> macros
# << macros

Summary:    An advanced log file viewer for the small-scale
Version:    0.12.0
Release:    0
Group:      Tools
License:    BSD-2-Clause
URL:        https://lnav.org
Source0:    %{name}-%{version}.tar.gz
Source100:  lnav.yaml
Requires:   sailfish-version >= 3.3.0
BuildRequires:  pkgconfig(sqlite3) > 3.13.0
BuildRequires:  pkgconfig(ncurses)
BuildRequires:  pkgconfig(libpcre)
BuildRequires:  pkgconfig(libpcre2-8)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  pkgconfig(libcurl)
BuildRequires:  pkgconfig(libarchive)
BuildRequires:  sailfish-version >= 3.3.0
BuildRequires:  gcc-c++
BuildRequires:  bzip2-devel
BuildRequires:  autoconf
BuildRequires:  automake
BuildRequires:  ( pkgconfig(readline) or readline-devel )

%description
%{summary}.

%if "%{?vendor}" == "chum"
Title: LNAV -- The Logfile Navigator
PackagedBy: nephros
Type: console-application
Categories:
  - Utility
  - FileTools
Custom:
  Repo: https://github.com/tstack/lnav
  PackagingRepo: https://github.com/sailfishos-chum/lnav
  DescriptionMD: https://raw.githubusercontent.com/tstack/lnav/master/README.md
Screenshots:
  - https://github.com/tstack/lnav/raw/master/docs/assets/images/lnav-syslog.png
%endif


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static \
    CFLAGS="$RPM_OPT_FLAGS -fPIC -pie" \
    CXXFLAGS="$RPM_OPT_FLAGS -fPIC -pie"


# >> build post
# out-of-the-box building fails with tools/bin2c.c:84: undefined reference to `compress'
# as this is only needed for building, lets just compile it manually here:
pushd tools
gcc $CFLAGS bin2c.c -o bin2c -lz
popd
pushd src
%make_build %{?_smp_mflags}
popd
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
pushd src
%make_install
popd
# << install post

%files
%defattr(-,root,root,-)
# >> files
%{_bindir}/%{name}
# << files
